=== mickours/simgrideclipse/Resources/inludes_source/article-jfacetext/src/cities.dtd
<!ELEMENT world (continent*)>

<!ELEMENT continent (description?,country*, ocean*)>
<!ATTLIST continent name CDATA #REQUIRED
                     population CDATA #IMPLIED>

<!ELEMENT country (description?,city*,attraction*)>
<!ATTLIST country name CDATA #REQUIRED
                     population CDATA #IMPLIED>
					 
<!ELEMENT city (description?,attraction*)>
<!ATTLIST city name CDATA #REQUIRED
                     population CDATA #IMPLIED>
					 
<!ELEMENT description (#PCDATA)>

<!ELEMENT attraction (description?)>
<!ATTLIST attraction name CDATA #REQUIRED>

<!ELEMENT ocean EMPTY>
<!ATTLIST ocean name CDATA #REQUIRED>

=== mickours/simgrideclipse/Resources/inludes_source/article-jfacetext/bin/cities.xml
<!DOCTYPE world SYSTEM "cities.dtd">
<world>
	<continent name = "Africa">
		<description>Easily the most beautiful continent</description>
	</continent>	
	<continent name = "North America">
		<country name = "USA" population = "250m">
			<description>Is &lt; people think</description>
			<city name = "New York">
				<attraction name = "Statue of Liberty"/>
				<attraction name = "Central Park"/>
			</city>
			<city name = "Los Angeles">
				<attraction name = "Hollywood"/>
			</city>
		</country>
		<country name = "Mexico" population = "250m"/>
		<ocean name = "atlantic"/>
		<ocean name = "pacific"/>
	</continent>
	<continent name = "Europe">
		<country name = "UK" population = "55m">
			<city name = "London">
				<description></description>
				<attraction name = "Big Ben"/>
				<attraction name = "Buckingham Palace">
					<description>
						<![CDATA[Where the queen lives > than most]]>
					</description>
				</attraction>
			</city>
			<city name = "Edinburgh">
				<attraction name = "Castle"/>
			</city>
			<attraction name = "Buckingham Palace"/>
		</country>
		<ocean name = "atlantic"/>		
	</continent>
</world>
